language: node_js
node_js:
- '8.9'
notifications:
  slack:
    secure: Q6mOrl/qyYlLadK9rzZCl2jAdlQcncGvOxa6rR16rDr/Uw206FVMih9GchUZ/b5cdNBXfmzOSzSnIa32mvAyPuQhBCKJy6FAM2xFDCBfbbH6J2zCSoLHwEo1e2jxuObx1pr12xVn2Fmvd8JD6Gt+x9cOrdHlv7js5SWu4ny6qfiQdnZU5GN4xsiRtNfijZNLttvAuSQ23TLGBNlxTA6jFetp5V+iSIDRKE3YAVM15pbXn/W5qz/AVkjg9/46QNpOFV+Ucl+cD0uigqgJf0rmk+fA+fHup8X5hpvkHXvEwrtsZuiO2KZADsOcWs26sfblpRhNhZiXFMMteQ22xe1axN9NaVdMg7wv6kFxucETOiST4lAF/0pPkxBGgrikQ+1JQ67JGyjHJZBtbFvhevN1WB3muK0lK+zLcuJkPiuiNyAUowwdCd/puXqXvt4zLibqqCfWrijbDjDpCRli9LpDEhp5b7NjmdGY4cjzP1l/AIxyNwIoE7kES+m5jHOtLBZBZ4obxNiRHLodFNrVfL9f2Qk2W8Jx6vPkrn6BdSN9UemUZk598HdpS8OM4m3+jNPGcdJlPfbzS61PWA7Hkm1mTnwzF5BhO9rf7TXBnOhk73o8HC2ReH3W2VD5ESHVOmTyd1adP8P8WFepQfPIVMP0mXdE2USPS9Ye6dTPFq8wLHw=
before_install:
- npm install -g bower grunt-cli
install:
- npm install
- bower install
before_script:
- grunt
